### ISSUE TITLE
Changing marker icon

### ISSUE THREAD

**Issue by ahmedsherpiny** [alexandrainst/alexandra-trackmap-panel#53]
Hi

I am using version 2.2.1 (from master) and i a trying to change the marker icon for Antpath with markers' visualization type

I replace marker.png in both src/img (as stated in the documentation) ans dist/img but the marker icon stays the sme

Could you please check it?

**Comment by tpachmann** [comment]
Hi @ahmedsherpiny!

I've wondered about this myself - the images stay the same, because they are compiled into the JS bundle.

So to change the markers you have to rebuild the plugin (as explained under "Development" in the README.md):
```
npm run-script build
```

Maybe I will add a feature to configure the markers directly in Grafana soon..

Best regards!
Tim

**Comment by j-or** [comment]
See https://github.com/alexandrainst/alexandra-trackmap-panel/pull/51 and https://github.com/alexandrainst/alexandra-trackmap-panel/pull/55
